# Program Settings 
config:
    mongo: 
        uri : "mongodb+srv://developartemis:ForABetterStockMarket2020@cluster0-j0aex.mongodb.net/develop?retryWrites=true&w=majority"
    gcp:
        service_account: ""
        
    
